user.email=naveenkharwar@hotmail.com
user.name=Naveen Kharwar
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
remote.origin.url=git@github.com:wayoutworks/awp.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.html.remote=origin
branch.html.merge=refs/heads/html
branch.master.remote=origin
branch.master.merge=refs/heads/master
